# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20170309_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
