# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followee',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='follower', to='cocktails.UserProfile'),
        ),
    ]
