# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_cocktail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
