# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_auto_20170314_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
