# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_cocktail_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='picture',
            field=models.ImageField(blank=True, upload_to='cocktail_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
